import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import React, { useState, } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';
import KeyboardArrowUpIcon from '@mui/icons-material/KeyboardArrowUp';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [accord,setAccord]=useState(true);

  const [array,setArray]=useState([
    {
      id:1,
      point:"MBA Online In Finance"
  },    {
      id:2,
      point:"MBA Online In Marketing"
  },    {
      id:3,
      point:"MBA Online In HR Management"
  },    {
      id:4,
      point:"MBA Online In IT Management"
  }
  ,    {
      id:5,
      point:"MBA Online Banking and Finance"
  }
  ,    {
      id:6,
      point:"MBA Online Business Analytics"
  }
  ,    {
      id:7,
      point:"MBA Online Healthcare"
  }
  ,    {
      id:8,
      point:"MBA Online International Business"
  },
  {
      id:9,
      point:"MBA Online Project Management"
  },    {
      id:10,
      point:"MBA Online Financial Markets"
  }
  ,    {
      id:11,
      point:"MBA Online Retail Management"
  },    {
      id:12,
      point:"MBA Online Banking Financial Insurance"
  }
  ,    {
      id:13,
      point:"MBA Online Hospital Administration"
  }
  ,    {
      id:14,
      point:"MBA Online International Trade Management"
  },    {
      id:15,
      point:"MBA Online Fintech"
  },    {
      id:16,
      point:"MBA Online Waste Management"
  }
  ,    {
      id:17,
      point:"MBA Online International Finance"
  }
  ,    {
      id:18,
      point:"MBA Online HR Analytics"
  },    {
      id:19,
      point:"MBA Online Digital entrepreneurship"
  },
  {
      id:20,
      point:"MBA Online Infrastructure Management"
  },{
      id:21,
      point:"MBA Online In Finance"
  },    {
      id:22,
      point:"MBA Online In Marketing"
  },    {
      id:23,
      point:"MBA Online In HR Management"
  },    {
      id:24,
      point:"MBA Online In IT Management"
  }
  ,    {
      id:25,
      point:"MBA Online Banking and Finance"
  }
  ,    {
      id:26,
      point:"MBA Online Business Analytics"
  }
  ,    {
      id:27,
      point:"MBA Online Healthcare"
  }
  ,    {
      id:28,
      point:"MBA Online International Business"
  },
  {
      id:29,
      point:"MBA Online Project Management"
  },    {
      id:30,
      point:"MBA Online Financial Markets"
  }
  ,    {
      id:31,
      point:"MBA Online Retail Management"
  },    {
      id:32,
      point:"MBA Online Banking Financial Insurance"
  }
  ,    {
      id:33,
      point:"MBA Online Hospital Administration"
  }
  ,    {
      id:34,
      point:"MBA Online International Trade Management"
  },    {
      id:35,
      point:"MBA Online Fintech"
  },    {
      id:36,
      point:"MBA Online Waste Management"
  }
  ,    {
      id:37,
      point:"MBA Online International Finance"
  }
  ,    {
      id:38,
      point:"MBA Online HR Analytics"
  },    {
      id:39,
      point:"MBA Online Digital entrepreneurship"
  },
  {
      id:40,
      point:"MBA Online Infrastructure Management"
  }
  ])

  const leftData = [];
  const rightData = [];

  array.forEach((item, index) => {
    if (index % 2 === 0) {
      leftData.push(item);
    } else {
      rightData.push(item);
    }
  });
const maxLength = Math.max(leftData.length, rightData.length);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
</div>
    <div className="table-responsive container">
     <div className='p-2 bg-success text-white fw-bold d-flex justify-content-between'><h4>In Demand Online MBA Course Specialization 2024</h4>{accord ? <KeyboardArrowDownIcon onClick={()=>setAccord(false)} /> : <KeyboardArrowUpIcon onClick={()=>setAccord(true)}/> } </div>
     {accord ? <table className="table table-bordered border-primary mt-4">
        <tbody>
          {[...Array(maxLength)].map((_, index) => (
            <tr key={index} >
              <td style={{ backgroundColor: index % 2 === 0 ? 'grey' : 'transparent',width:"50%" }}>{leftData[index] ? leftData[index].point : ''}</td>
              <td style={{ backgroundColor: index % 2 === 0 ? 'grey' : 'transparent',width:"50%" }}>{rightData[index] ? rightData[index].point : ''}</td>
            </tr>
          ))}
        </tbody>
      </table> : "" }
    </div>
    
    </>
  )
}
